//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memento.Common.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memento.Common.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answers will be evaluated by the app..
        /// </summary>
        public static string AutomaticModeHint {
            get {
                return ResourceManager.GetString("AutomaticModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Add Сloze&quot; button..
        /// </summary>
        public static string CardCreateHelpClickAddText {
            get {
                return ResourceManager.GetString("CardCreateHelpClickAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Create&quot; button to finish..
        /// </summary>
        public static string CardCreateHelpClickCreateText {
            get {
                return ResourceManager.GetString("CardCreateHelpClickCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste new card text bellow..
        /// </summary>
        public static string CardCreateHelpPasteText {
            get {
                return ResourceManager.GetString("CardCreateHelpPasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select word(s) for cloze deletion..
        /// </summary>
        public static string CardCreateHelpSelectText {
            get {
                return ResourceManager.GetString("CardCreateHelpSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficient used to calculate the next delay..
        /// </summary>
        public static string CoefficientHint {
            get {
                return ResourceManager.GetString("CoefficientHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will choose between smooth or sharp penalty..
        /// </summary>
        public static string CombinedDelayModeHint {
            get {
                return ResourceManager.GetString("CombinedDelayModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of steps the card will move the first time. Corresponds to lower bound of memory span..
        /// </summary>
        public static string FirstDelayHint {
            get {
                return ResourceManager.GetString("FirstDelayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle cards.
        /// </summary>
        public static string IsShuffled {
            get {
                return ResourceManager.GetString("IsShuffled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will tell the app if you were right or wrong after seeing the correct answer..
        /// </summary>
        public static string ManualModeHint {
            get {
                return ResourceManager.GetString("ManualModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your answer..
        /// </summary>
        public static string PleaseEnterYourAnswer {
            get {
                return ResourceManager.GetString("PleaseEnterYourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of steps the card will move the second time. Corresponds to upper bound of memory span..
        /// </summary>
        public static string SecondDelayHint {
            get {
                return ResourceManager.GetString("SecondDelayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answer will change delay to the initial value..
        /// </summary>
        public static string SharpDelayModeHint {
            get {
                return ResourceManager.GetString("SharpDelayModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answer will change delay to the previous value..
        /// </summary>
        public static string SmoothDelayModeHint {
            get {
                return ResourceManager.GetString("SmoothDelayModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of steps the card will move the first time..
        /// </summary>
        public static string StartDelayHint {
            get {
                return ResourceManager.GetString("StartDelayHint", resourceCulture);
            }
        }
    }
}
