// <auto-generated />
namespace Memento.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropAnswercolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropAnswercolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201511011808506_Drop Answer column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
