// <auto-generated />
namespace Memento.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addcolumnforshareddecks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcolumnforshareddecks));
        
        string IMigrationMetadata.Id
        {
            get { return "201606051922323_Add column for shared decks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
